[package]
name = "axruntime"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Runtime library of ArceOS"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/modules/axruntime"
documentation = "https://rcore-os.github.io/arceos/axruntime/index.html"

[features]
default = []

smp = ["axhal/smp"]
irq = ["axhal/irq", "axtask?/irq", "percpu", "kernel_guard"]
tls = ["axhal/tls", "axtask?/tls"]
alloc = ["axalloc"]
paging = ["axhal/paging", "lazy_init"]

multitask = ["axtask/multitask"]
fs = ["axdriver", "axfs"]
net = ["axdriver", "axnet"]
display = ["axdriver", "axdisplay"]
signal = ["axprocess/signal", "axhal/signal"]
img = ["axdriver/img"]
monolithic = ["axprocess/monolithic", "axhal/monolithic", "axtask/monolithic", "axmem/monolithic"]

[dependencies]
cfg-if = "1.0"
axhal = { git = "https://github.com/Arceos-crates/axhal.git" }
axlog = { git = "https://github.com/Arceos-crates/axlog.git" }
axconfig = { git = "https://github.com/Arceos-crates/axconfig.git"}
axalloc = { git = "https://github.com/Arceos-crates/axalloc.git", optional = true }
axdriver = { git = "https://github.com/Arceos-crates/axdriver.git", optional = true }
axfs = { path = "../axfs", optional = true }
axnet = { path = "../axnet", optional = true }
axdisplay = { path = "../axdisplay", optional = true }
axtask = { git = "https://github.com/Arceos-crates/axtask.git", optional = true }
axprocess = { path = "../axprocess", optional = true }
axmem = { path = "../axmem", optional = true }
crate_interface = { git = "https://github.com/Arceos-crates/crate_interface.git" }
percpu = { git = "https://github.com/Arceos-crates/percpu.git", optional = true }
kernel_guard = { git = "https://github.com/Arceos-crates/kernel_guard.git", optional = true }
lazy_init = { git = "https://github.com/Arceos-crates/lazy_init.git" , optional = true }