[package]
name = "arceos-udpserver"
version = "0.1.0"
edition = "2021"
authors = ["Dashuai Wu <wudashuaijss@foxmail.com>"]

[dependencies]
axstd = { git = "https://github.com/Arceos-crates/axstd.git", features = ["net"], optional = true }
