[package]
name = "axsync"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "ArceOS synchronization primitives"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/modules/axsync"
documentation = "https://rcore-os.github.io/arceos/axsync/index.html"

[features]
multitask = ["axtask/multitask"]
default = []

[dependencies]
spinlock = { git = "https://github.com/Arceos-crates/spinlock.git" }
axtask = { git = "https://github.com/Arceos-crates/axtask.git" }

[dev-dependencies]
rand = "0.8"
axsync = { path = ".", features = ["multitask"] }
axtask = { git = "https://github.com/Arceos-crates/axtask.git", features = ["test"] }
