[package]
name = "danger_access"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axstd = { git = "https://github.com/Arceos-crates/axstd.git", features = ["multitask", "alloc"], optional = true }