[package]
name = "arceos_posix_api"
version = "0.1.0"
edition = "2021"
authors = [
    "Yuekai Jia <equation618@gmail.com>",
    "yanjuguang <coolyanjg@163.com>",
    "wudashuai <wu-ds20@mails.tsinghua.edu.cn>",
    "yfblock <321353225@qq.com>",
    "scPointer <bhy18@mails.tsinghua.edu.cn>",
    "Shiping Yuan <robert_yuan@pku.edu.com>",
]
description = "POSIX-compatible APIs for ArceOS modules"
license = "GPL-3.0-or-later OR Apache-2.0"
repository = "https://github.com/rcore-os/arceos/tree/main/api/arceos_posix_api"

[features]
default = []

smp = ["axfeat/smp"]
alloc = ["dep:axalloc", "axfeat/alloc"]
multitask = ["axtask/multitask", "axfeat/multitask", "axsync/multitask"]
fd = ["alloc"]
fs = ["dep:axfs", "axfeat/fs", "fd"]
net = ["dep:axnet", "axfeat/net", "fd"]
pipe = ["fd"]
select = ["fd"]
epoll = ["fd"]

[dependencies]
# ArceOS modules
axfeat = { path = "../axfeat" }
axruntime = { git = "https://github.com/Arceos-crates/axruntime.git" }
axconfig = { git = "https://github.com/Arceos-crates/axconfig.git" }
axlog = { git = "https://github.com/Arceos-crates/axlog.git" }
axhal = { git = "https://github.com/Arceos-crates/axhal.git" }
axsync = { git = "https://github.com/Arceos-crates/axsync.git" }
axalloc = { git = "https://github.com/Arceos-crates/axalloc.git", optional = true }
axtask = { git = "https://github.com/Arceos-crates/axtask.git", optional = true }
axfs = { git = "https://github.com/Arceos-crates/axfs.git", optional = true }
axnet = { git = "https://github.com/Arceos-crates/axnet.git", optional = true }

# Other crates
axio = { git = "https://github.com/Arceos-crates/axio" }
axerrno = { git = "https://github.com/Arceos-crates/axerrno.git" }
static_assertions = "1.1.0"
spin = { version = "0.9" }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
flatten_objects = { git = "https://github.com/Arceos-crates/flatten_objects.git" }

[build-dependencies]
bindgen ={ version = "0.66" }
